### ISSUE TITLE
[Feature Request] GUI

### ISSUE THREAD

**Issue by axeldelafosse** [axeldelafosse/stemgen#16]
I just discovered [RipX](https://hitnmix.com) and I have to admit: having a nice GUI would be a cool addition. It would be even better if it was a web app!

**Comment by benjaminlewandowski** [comment]
i would love to help design wise. if you really want to do a web app i am eager to help there too (especially with the front end part)

**Comment by axeldelafosse** [comment]
I realized that using Ableton Live as a GUI is probably best. So I found a way to automate the export of stems directly from Ableton: https://github.com/axeldelafosse/stemgen/blob/master/ableton.py

**Comment by axeldelafosse** [comment]
Closing this -- I'll add more docs in the future and communicate properly when it's ready.
