### ISSUE TITLE
[Feature Request] MP3 support

### ISSUE THREAD

**Issue by stathius** [axeldelafosse/stemgen#18]
Why not add mp3 support? I manually added it in the supported types and seems to work fine.

**Comment by benjaminlewandowski** [comment]
My guess is that extracting the stems from a lossy file isn't as accurate.

**Comment by stathius** [comment]
It worked well for a couple of tracks that I tried. A lot of people have their music library in mp3s so it would probably be beneficial to add this option.

**Comment by axeldelafosse** [comment]
Hey! Sorry but I don't want to encourage people to separate stems from lossy formats. We need to encode to WAV when using Demucs, so it's pretty bad to use MP3 files as input. You shouldn't do this.

**Comment by MacTheZazou** [comment]
@axeldelafosse I can't find any information that back up the fact that using lossy formats as input is bad with DEMUCS... In fact DEMUCS is trained with lossy audio:

> All files from the musdb18 dataset are encoded in the [Native Instruments stems format](http://www.stems-music.com/)[ (opens new window)](http://www.stems-music.com/) (.mp4). It is a multitrack format composed of 5 stereo streams, each one encoded in AAC @256kbps.

**Comment by MacTheZazou** [comment]
You're right, I didn't follow the link correctly. Thank you for your work, it's incredible. I would love to do a Blind-test on some big PA though.

**Comment by axeldelafosse** [comment]
Thank you, really appreciate it.

Yeah to be honest I'm not sure I understand exactly how Demucs is impacting the audio quality. I'll try to dig into that at some point.

**Comment by CarlosLeonCode** [comment]
I read the thread... I use to do is the following:
- I have music in mp3 - 320kbps. This is the best format in mp3
- I process the tracks in fadr or Moises, this exports the stems as .mp3 (that means that I've to convert them)
- I process the stems in Ableton Live (exporting them in .wav) and the into StemCreator
- Finally I get my stems to use them into rekordbox

Having this in mind, why not create a functionality to convert mp3 - 320kbps to wav and then can create the stems? I could help with this feature.
