### ISSUE TITLE
Feature request: Batch a whole directory of tracks

### ISSUE THREAD

**Issue by CorgiMan** [axeldelafosse/stemgen#2]
Would be nice if you can just run the command on a whole directory of files.

**Comment by CorgiMan** [comment]
In the meanwhile using this command:

`for s in ~/Music/todo/*; do if [ ! -f "/Users/wieger/src/petprojects/stemgen/output/${$(basename $s):0:-4}.stem.m4a" ]; then ./stemgen -i $s; fi ; done`

**Comment by axeldelafosse** [comment]
Closing this because I don't intend to add more support for this feature. You can either create your own wrapper (I'm personally using Stemgen in a NestJS API with a proper queue) or you can use the droplet on macOS
