### ISSUE TITLE
Mutagen missing in installation instructions

### ISSUE THREAD

**Issue by XPerianer** [axeldelafosse/stemgen#30]
I followed the installation instructions for Mac, and when trying to create a stemgen python3 complained about missing mutagen package.
Installation of this should be reflected in the installation instructions, e.g.:
```python3 -m pip install -U demucs mutagen```

**Comment by axeldelafosse** [comment]
Thank you for the suggestion. Fixed in https://github.com/axeldelafosse/stemgen/commit/135108ac7848ac5a08eccc7530aeee3ab47ce213.
