### ISSUE TITLE
[Feature request] Extract only vocals and instrumental

### ISSUE THREAD

**Issue by frabaldan** [axeldelafosse/stemgen#32]
I think it would be nice to have an option to separate just vocals and instrumental track, is this possible?

**Comment by axeldelafosse** [comment]
Hey! Thank you for your request. This is out of scope because the goal is to create stem files with at least 4 stems.

If you really want to use only two stems, it is possible but you will have to modify the code yourself. Have fun :)

**Comment by lolgithub** [comment]
@frabaldan : if you want advice on how to do this, or you really really want a quick and dirty patch, feel free to send me a dm here on github.

**Comment by frabaldan** [comment]
Thanks for the response. Will try!
