### ISSUE TITLE
[Feature request] Custom name & color for stem

### ISSUE THREAD

**Issue by MacTheZazou** [axeldelafosse/stemgen#36]
I would like to customize the name & color of the different stem, is it possible? My goal is to include the key of each stem by running libkeyfinder from mixxxdj just after stem separation. I can modify the code myself to include libkeyfinder, but can't find a way for custom naming & Would find nice to set custom color to the different stem with hex cli option.

**Comment by Ma5onic** [comment]
You just need to edit the metadata.json file

**Comment by axeldelafosse** [comment]
You can do this programmatically by using the `create_metadata_json` function in `metadata.py`.

Closing this issue as I'm not planning to add this as a CLI option.
