### ISSUE TITLE
[Feature Request] Following the Stem File Specification

### ISSUE THREAD

**Issue by Ma5onic** [axeldelafosse/stemgen#38]
Is there a reason that you aren't following the stem file specification and using M4A instead of MP4? 
I marked this as a feature request, but I've never seen a stem file using m4a. To my understanding, the only difference between the two is the file extension, the file contents are the same.

According to NI's Programmers' Reference:
```
There are two criteria every Stem File must fulfill—failure to fulfill these criteria means the file
in question is not a Stem File:
▪ The file must be a valid MP4 file (ISO base media file format: ISO/IEC 14496-12) with the
    “.mp4” file extension. Preferably the file name should end with “.stem.mp4”, but just
    “.mp4” is also valid.
▪ The MP4 file must contain a box (i.e. data container) of type stem as a sub-box of
moov.udta. moov is the root box of the MP4 file, as shown in the Stem File Structure
diagram in section ↑7.1, File Structure.
```

[Stem File Specification English.pdf](https://github.com/axeldelafosse/stemgen/files/12771079/Stem.File.Specification.English.pdf)

**Comment by axeldelafosse** [comment]
`.m4a` means mp4 audio, it's a perfectly valid extension.
