### ISSUE TITLE
Google Colab version?

### ISSUE THREAD

**Issue by broken** [axeldelafosse/stemgen#41]
Have you tried running this on Google colab or have a notebook available?

Demucs cooks my laptop, and I noticed they had a [colab](https://colab.research.google.com/drive/1dC9nVxk3V_VPjUADsnFu8EiT-xnU1tGH?usp=sharing#scrollTo=kMKN9BN4r37E) available.  Then while looking for a library to convert the output to Traktor's stem files, I ran across this repo. Is ni-stems a library you wrote?

**Comment by axeldelafosse** [comment]
Hey! No, I haven't tried but it should work!

`ni-stem` is an open-source library by Native Instruments, but they haven't updated it in a while. You can use the original version by downloading it from their website. Or you can use the updated and improved version included in this repo.

Let me know if you write a notebook, I'll put the link in the README. Thank you!
