### ISSUE TITLE
Getting an error, when running the docker script version.

### ISSUE THREAD

**Issue by Galabov93** [axeldelafosse/stemgen#45]
Everything is fine and files are being created, but on the last step, (After 'Done 5/6' log)
I get the following error message:
` /stemgen/ni-stem/GPAC_linux/MP4Box: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory`

The environment is WSL2 on Windows 11

**Comment by UglyGit** [comment]
I have the exact same issue. I modified the Dockerfile to apt install openssl, thinking that might help but it didn't.  Sooo close. Anyone have solution/suggestions 
Cheers

**Comment by axeldelafosse** [comment]
Sorry I haven't created this Dockerfile and doesn't intend to maintain it. Please send a PR if you found the issue!

Closing this for now. You can follow the installation steps for Windows in the docs at [stemgen.dev](https://stemgen.dev/docs/installation)
