### ISSUE TITLE
mp3 processing

### ISSUE THREAD

**Issue by CarlosLeonCode** [axeldelafosse/stemgen#48]
Hi, This is a nice project. I was exploring it because I need to create some stems and I'm too lazy to make them by hand. When I executed the .py file, I received a message in console that says that I must to use other audio file format instead of mp3. Why I can't use mp3? 

If we can't use, I think I'll be useful convert the input if the format file is mp3.

**Comment by kartguru** [comment]
Refer to #18 @CarlosLeonCode
