### ISSUE TITLE
Batch processing with stemgen

### ISSUE THREAD

**Issue by djmow** [axeldelafosse/stemgen#52]
How can I can convert multiple songs at once instead of one by one. Please I need help

**Comment by kartguru** [comment]
See comments in #31

**Comment by djmow** [comment]
> See comments in #31

i saw it, how can i create the script  what is the source and the command to use, i dont really understand much about code but i can convert one by one but i just need the batch process to speed up my process. Thanks in advance

**Comment by djmow** [comment]
> > See comments in #31
> 
> i saw it, how can i create the script what is the source and the command to use, i dont really understand much about code but i can convert one by one but i just need the batch process to speed up my process. Thanks in advance

Pls little guides
