### ISSUE TITLE
Failing when trying to find files with numbers appended.

### ISSUE THREAD

**Issue by TijuanaKez** [axeldelafosse/stemgen#53]
Starts off ok and find the file and ffmpeg does some things successfully, but it eventually fails here every time.
```
[in#0 @ 0x7f93918046c0] Error opening input: No such file or directory
Error opening input file /Users/me/Desktop/Fuego.1.aiff."
```
It doesn't matter what file it is or where it resides, it's always trying to find my input file with a ".1" after it, in the same folder, but it never exists.
On a Mac Sonoma.

thanks.

**Comment by axeldelafosse** [comment]
I think that you are using `stem.py` instead of `stemgen.py` -- can you double-check?
