### ISSUE TITLE
[Feature Request] GPU acceleration

### ISSUE THREAD

**Issue by axeldelafosse** [axeldelafosse/stemgen#9]
Following this discussion: https://github.com/axeldelafosse/stemgen/issues/8#issuecomment-1358661602 -- I think Stemgen should:

- [ ] Default to GPU
- [ ] Provide a flag to force CPU
- [ ] Explain how to get Spleeter and/or Demucs to work with Mac GPUs

**Comment by 0vm** [comment]
Don't default to GPU as many people will be running this on dockers, VM's, etc. These don't have GPUs and if anyone wants to switch to GPU, include something in the README such as removing the CPU Flag.

**Comment by awesomer** [comment]
I think it's fine to default to GPU... *if* the underlying tool
automatically and reliably falls back to CPU if GPU is not available.
Otherwise, I agree that CPU should be the default.

**Comment by 0vm** [comment]
I disagree as what if the GPU has very bad performance, shared memory with
RAM, etc. An option in the README will be much more convenient as people
who are interested in using the GPU will use the GPU while CPU option works
on every device.

**Comment by awesomer** [comment]
There are cases where GPU acceleration has worse performance than CPU?

**Comment by benjaminlewandowski** [comment]
> There are cases where GPU acceleration has worse performance than CPU?

I think that some gpu/cpu combinations could be slower with cuda - but it should be the exception

Using gpu is around 15 times faster with my mobile 3070 instead of my 10th gen 16 thread I7.

I will also test this with a 11th gen i5/ mobile 1650 gpu combo

**Comment by axeldelafosse** [comment]
Yeah! I'm gonna work on this soon!

**Comment by MacTheZazou** [comment]
It's quite easy to use GPU with stemgen:

1.  Follow the GPU step of DEMUCS setup:
    If you are using Windows: [Windows support](https://github.com/facebookresearch/demucs/blob/main/docs/windows.md).
    If you are using MAC OS X: [Mac OS X support](https://github.com/facebookresearch/demucs/blob/main/docs/mac.md).
    If you are using Linux: [Linux support](https://github.com/facebookresearch/demucs/blob/main/docs/linux.md).
    
2. replace all occurence of
`"-d",
                "cpu",`
for
`"-d",
                "cuda",`

in stemgen.py

**Comment by axeldelafosse** [comment]
Hey! I took some time to write proper docs and add support for GPU without touching the code: https://stemgen.dev/docs/gpu-acceleration-on-windows.

Note that it is only working on Windows if you have a NVIDIA GPU.
